spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
  datasource:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://hackathondbfinal.cyiztsnfihih.ap-northeast-2.rds.amazonaws.com/hackathon
chatgpt:
  api:
    endpoint: https://api.openai.com/v1/chat/completions
    key:
  tts:
    endpoint: https://api.openai.com/v1/tts/synthesize
server:
  port: '80'
jwt:
  secret-key:
oauth:
  kakao:
    client-id:
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com